# ===== APLICACIÓN =====
spring.application.name=GymSystem
server.port=8080

# ===== BASE DE DATOS (Aiven.io) =====
# Reemplaza con tus credenciales de Aiven.io
spring.datasource.url=jdbc:mysql://examen-02-base-de-datos.c.aivencloud.com:18296/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ZdbK1ffimtnHWHC9VAz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JDBC =====
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# ===== THYMELEAF =====
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===== CORREO (para recuperar contraseña) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joseangelmontoya69@gmail.com
spring.mail.password=rtxy pkvx nccj mlqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== LOGGING =====
logging.level.com.gym=DEBUG
logging.level.org.springframework.security=DEBUG
